version: "3.5"

services:
  db:
    image: mysql:8.0.27
    container_name: www-db
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    volumes:
      - "./preset:/docker-entrypoint-initdb.d"
      - "www-db-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-test
    restart: always
    depends_on:
      - db
    ports:
      - 11111:80

volumes:
  www-db-data:
    name: db-data
